FROM node:12-alpine as builder
WORKDIR /app
COPY . /app/
RUN npm install
RUN npm run build

FROM nginx:1.18.0-alpine
RUN mkdir -p /usr/share/nginx/html/dev.hayuna.pl
RUN mkdir -p /etc/nginx/sites-available/dev.hayuna.pl
COPY --from=builder /app/dist/ /usr/share/nginx/html/dev.hayuna.pl
RUN ln -s /etc/nginx/sites-available/dev.hayuna.pl /etc/nginx/sites-enabled/dev.hayuna.pl
COPY nginx.dev.conf /etc/nginx/sites-available/dev.hayuna.pl