FROM node:12-alpine as builder
WORKDIR /app
COPY . /app/
RUN npm install
RUN npm run build

FROM nginx:1.18.0-alpine
COPY --from=builder /app/dist/ /usr/share/nginx/html
RUN mkdir -p /etc/nginx/sites-available
RUN ln -s /etc/nginx/sites-available /etc/nginx/sites-enabled
COPY nginx.dev.conf /etc/nginx/conf.d/default.conf
COPY nginx.dev.conf /etc/nginx/sites-available/dev.hayuna.pl