version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    command: node src/server.js
    container_name: DEV_api
    ports:
      - 4000:4000
    restart: always
    volumes:
      - ./server:/app/server
      - /var/run/docker.sock:/tmp/docker.sock:ro
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: DEV_client
    links:
      - server
    ports:
      - 80:80
    restart: always
    volumes:
      - ./server/logos:/usr/share/nginx/html/logos
      - ./client:/app/client
      - /var/run/docker.sock:/tmp/docker.sock:ro