version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: node src/server.js
    container_name: api${PORT}
    restart: always
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client${PORT}
    links:
      - server
    ports:
      - ${PORT}:80
    restart: always
    volumes:
      - ./server/logos:/usr/share/nginx/html/logos
