version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: dockerfile.dev
    command: node src/server.js
    container_name: DEV_api
    environment:
      - PORT=4000
      - VIRTUAL_HOST=2000
    ports:
      - 4000:4000
    restart: always
    volumes:
      - ./server/src:/app/server/src
  client:
    build:
      context: ./client
      dockerfile: dockerfile.dev
    container_name: DEV_client
    links:
      - server
    ports:
      - 81:81
      - 443:443
    restart: always
    volumes:
      - ./server/logos:/usr/share/nginx/html/logos