name: DEVELOPER CI

on:
  push:
    branches:
      - developer

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        timeout: 30m
        command_timeout: 60m  
        script: |
          cd /home/live-sharing/developer
          git pull origin developer
          ls -al
          npm run install:all
          npm run docker-compose:dev:restart
