name: CI

on:
  pull_request
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        timeout: 30m
        command_timeout: 60m  
        script: |
          echo ${{github}}
          echo ${{github.event}}
          echo ${{github.event_path}}
          echo ${{github.workflow}}
          echo ${{github.job}}
          echo ${{github.run_id}}
          echo ${{github.run_number}}
          echo ${{github.actor}}
          echo ${{github.repository}}
          echo ${{github.repository_owner}}
          echo ${{github.event_name}}
          echo ${{github.sha}}
          echo ${{github.ref}}
          echo ${{github.head_ref}}
          echo ${{github.base_ref}}
          echo ${{github.token}}
          echo ${{github.workspace}}
          echo ${{github.action}}
        #   mkdir -p /home/live-sharing/developer${{GITHUB_RUN_NUMBER+200}}
        #   cd /home/live-sharing/developer${{GITHUB_RUN_NUMBER+200}}
        #   git remote add origin https://github.com/hayuna/devrelease_heroku
        #   git clone https://github.com/hayuna/devrelease_heroku .
        #   git checkout master
        #   git pull origin master
        #   npm run install:all
        #   docker-compose down -v
        #   echo "PORT=${{GITHUB_RUN_NUMBER+200}}" >> "./.env"
        #   docker-compose up --build -d