name: CI

on:
  pull_request
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        timeout: 30m
        command_timeout: 60m  
        script: |
          mkdir -p /home/live-sharing/${{github.head_ref}}
          cd /home/live-sharing/${{github.head_ref}}
          git remote add origin https://github.com/hayuna/devrelease_heroku
          git clone https://github.com/hayuna/devrelease_heroku .
          git checkout ${{github.head_ref}}
          git pull origin ${{github.head_ref}}
          npm run install:all
          docker-compose down -v
          echo "PORT=10${{github.event.pull_request.number}}" >> "./.env"
          docker-compose up --build -d